-- local fzf_lua = require('fzf-lua')
-- vim.keymap.set('n', '<leader>f', fzf_lua.files, {})
-- vim.keymap.set('n', '<leader><space>', fzf_lua.buffers, {})
-- -- vim.keymap.set('n', '<leader>fc', fzf_lua.command_history, {})
-- vim.keymap.set('n', '<leader>m', fzf_lua.marks, {})
-- vim.keymap.set('n', '<leader>r', fzf_lua.lsp_references, {})

-- vim.keymap.set('n', '<leader>g', function()
-- 	fzf_lua.grep_string({ search = vim.fn.input('Grep: ') })
-- end)
