set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

set guifont=Hack\ Nerd\ Font\ Regular\ 12

colorscheme base16-ateliercave

set lines=999 columns=999

highlight clear ALEErrorSign
highlight clear ALEWarningSign
let g:ale_sign_error = '💩'
let g:ale_sign_warning = '🤔'

set completefunc=emoji#complete
